package com.hamadaintranet.entity;
// Generated Oct 13, 2020 10:20:22 AM by Hibernate Tools 5.2.10.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Categories generated by hbm2java
 */
@Entity
@Table(name = "categories", catalog = "hamadadb")
public class Categories implements java.io.Serializable {

	private long categoryId;
	private String cateName;
	private Set<Products> productses = new HashSet<Products>(0);

	public Categories() {
	}

	public Categories(long categoryId, String cateName) {
		this.categoryId = categoryId;
		this.cateName = cateName;
	}

	public Categories(long categoryId, String cateName, Set<Products> productses) {
		this.categoryId = categoryId;
		this.cateName = cateName;
		this.productses = productses;
	}

	@Id

	@Column(name = "category_id", unique = true, nullable = false)
	public long getCategoryId() {
		return this.categoryId;
	}

	public void setCategoryId(long categoryId) {
		this.categoryId = categoryId;
	}

	@Column(name = "cate_name", nullable = false, length = 60)
	public String getCateName() {
		return this.cateName;
	}

	public void setCateName(String cateName) {
		this.cateName = cateName;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "categories")
	public Set<Products> getProductses() {
		return this.productses;
	}

	public void setProductses(Set<Products> productses) {
		this.productses = productses;
	}

}
