package com.hamadaintranet.entity;
// Generated Oct 13, 2020 10:20:22 AM by Hibernate Tools 5.2.10.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;

/**
 * Clients generated by hbm2java
 */
@Entity
@Table(name = "clients", catalog = "hamadadb", uniqueConstraints = {
		@UniqueConstraint(columnNames = "cli_company_cnpj"), @UniqueConstraint(columnNames = "cli_company_ie"),
		@UniqueConstraint(columnNames = "cli_company_phone_number"), @UniqueConstraint(columnNames = "cli_cpf"),
		@UniqueConstraint(columnNames = "cli_email"), @UniqueConstraint(columnNames = "cli_phone_number_two"),
		@UniqueConstraint(columnNames = "cli_phone_number"), @UniqueConstraint(columnNames = "cli_rg") })
public class Clients implements java.io.Serializable {

	private long cliId;
	private Date cliRegDate;
	private String cliName;
	private String cliRg;
	private String cliCpf;
	private String cliPhoneCode;
	private String cliPhoneNumber;
	private String cliPhoneCodeTwo;
	private String cliPhoneNumberTwo;
	private String cliEmail;
	private String cliCompany;
	private String cliCompanyCnpj;
	private String cliCompanyIe;
	private String cliCompanyPhoneCode;
	private String cliCompanyPhoneNumber;
	private String cliCompanyEmail;
	private String cliCompanyAddr;
	private String cliCompanyAddrNum;
	private String cliCompanyPostal;
	private String cliCompanyDistrict;
	private String cliCompanyCity;
	private String cliCompanyState;
	private String cliPassword;
	private Set<ProductOrder> productOrders = new HashSet<ProductOrder>(0);
	private Set<Reviews> reviewses = new HashSet<Reviews>(0);

	public Clients() {
	}

	public Clients(long cliId, Date cliRegDate, String cliName, String cliRg, String cliCpf, String cliPhoneCode,
			String cliPhoneNumber, String cliCompany, String cliCompanyCnpj, String cliCompanyIe,
			String cliCompanyPhoneCode, String cliCompanyPhoneNumber, String cliCompanyAddr, String cliCompanyAddrNum,
			String cliCompanyPostal, String cliCompanyDistrict, String cliCompanyCity, String cliCompanyState,
			String cliPassword) {
		this.cliId = cliId;
		this.cliRegDate = cliRegDate;
		this.cliName = cliName;
		this.cliRg = cliRg;
		this.cliCpf = cliCpf;
		this.cliPhoneCode = cliPhoneCode;
		this.cliPhoneNumber = cliPhoneNumber;
		this.cliCompany = cliCompany;
		this.cliCompanyCnpj = cliCompanyCnpj;
		this.cliCompanyIe = cliCompanyIe;
		this.cliCompanyPhoneCode = cliCompanyPhoneCode;
		this.cliCompanyPhoneNumber = cliCompanyPhoneNumber;
		this.cliCompanyAddr = cliCompanyAddr;
		this.cliCompanyAddrNum = cliCompanyAddrNum;
		this.cliCompanyPostal = cliCompanyPostal;
		this.cliCompanyDistrict = cliCompanyDistrict;
		this.cliCompanyCity = cliCompanyCity;
		this.cliCompanyState = cliCompanyState;
		this.cliPassword = cliPassword;
	}

	public Clients(long cliId, Date cliRegDate, String cliName, String cliRg, String cliCpf, String cliPhoneCode,
			String cliPhoneNumber, String cliPhoneCodeTwo, String cliPhoneNumberTwo, String cliEmail, String cliCompany,
			String cliCompanyCnpj, String cliCompanyIe, String cliCompanyPhoneCode, String cliCompanyPhoneNumber,
			String cliCompanyEmail, String cliCompanyAddr, String cliCompanyAddrNum, String cliCompanyPostal,
			String cliCompanyDistrict, String cliCompanyCity, String cliCompanyState, String cliPassword,
			Set<ProductOrder> productOrders, Set<Reviews> reviewses) {
		this.cliId = cliId;
		this.cliRegDate = cliRegDate;
		this.cliName = cliName;
		this.cliRg = cliRg;
		this.cliCpf = cliCpf;
		this.cliPhoneCode = cliPhoneCode;
		this.cliPhoneNumber = cliPhoneNumber;
		this.cliPhoneCodeTwo = cliPhoneCodeTwo;
		this.cliPhoneNumberTwo = cliPhoneNumberTwo;
		this.cliEmail = cliEmail;
		this.cliCompany = cliCompany;
		this.cliCompanyCnpj = cliCompanyCnpj;
		this.cliCompanyIe = cliCompanyIe;
		this.cliCompanyPhoneCode = cliCompanyPhoneCode;
		this.cliCompanyPhoneNumber = cliCompanyPhoneNumber;
		this.cliCompanyEmail = cliCompanyEmail;
		this.cliCompanyAddr = cliCompanyAddr;
		this.cliCompanyAddrNum = cliCompanyAddrNum;
		this.cliCompanyPostal = cliCompanyPostal;
		this.cliCompanyDistrict = cliCompanyDistrict;
		this.cliCompanyCity = cliCompanyCity;
		this.cliCompanyState = cliCompanyState;
		this.cliPassword = cliPassword;
		this.productOrders = productOrders;
		this.reviewses = reviewses;
	}

	@Id

	@Column(name = "cli_id", unique = true, nullable = false)
	public long getCliId() {
		return this.cliId;
	}

	public void setCliId(long cliId) {
		this.cliId = cliId;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "cli_reg_date", nullable = false, length = 10)
	public Date getCliRegDate() {
		return this.cliRegDate;
	}

	public void setCliRegDate(Date cliRegDate) {
		this.cliRegDate = cliRegDate;
	}

	@Column(name = "cli_name", nullable = false, length = 80)
	public String getCliName() {
		return this.cliName;
	}

	public void setCliName(String cliName) {
		this.cliName = cliName;
	}

	@Column(name = "cli_rg", unique = true, nullable = false, length = 20)
	public String getCliRg() {
		return this.cliRg;
	}

	public void setCliRg(String cliRg) {
		this.cliRg = cliRg;
	}

	@Column(name = "cli_cpf", unique = true, nullable = false, length = 14)
	public String getCliCpf() {
		return this.cliCpf;
	}

	public void setCliCpf(String cliCpf) {
		this.cliCpf = cliCpf;
	}

	@Column(name = "cli_phone_code", nullable = false, length = 2)
	public String getCliPhoneCode() {
		return this.cliPhoneCode;
	}

	public void setCliPhoneCode(String cliPhoneCode) {
		this.cliPhoneCode = cliPhoneCode;
	}

	@Column(name = "cli_phone_number", unique = true, nullable = false, length = 9)
	public String getCliPhoneNumber() {
		return this.cliPhoneNumber;
	}

	public void setCliPhoneNumber(String cliPhoneNumber) {
		this.cliPhoneNumber = cliPhoneNumber;
	}

	@Column(name = "cli_phone_code_two", length = 2)
	public String getCliPhoneCodeTwo() {
		return this.cliPhoneCodeTwo;
	}

	public void setCliPhoneCodeTwo(String cliPhoneCodeTwo) {
		this.cliPhoneCodeTwo = cliPhoneCodeTwo;
	}

	@Column(name = "cli_phone_number_two", unique = true, length = 9)
	public String getCliPhoneNumberTwo() {
		return this.cliPhoneNumberTwo;
	}

	public void setCliPhoneNumberTwo(String cliPhoneNumberTwo) {
		this.cliPhoneNumberTwo = cliPhoneNumberTwo;
	}

	@Column(name = "cli_email", unique = true, length = 70)
	public String getCliEmail() {
		return this.cliEmail;
	}

	public void setCliEmail(String cliEmail) {
		this.cliEmail = cliEmail;
	}

	@Column(name = "cli_company", nullable = false, length = 120)
	public String getCliCompany() {
		return this.cliCompany;
	}

	public void setCliCompany(String cliCompany) {
		this.cliCompany = cliCompany;
	}

	@Column(name = "cli_company_cnpj", unique = true, nullable = false, length = 18)
	public String getCliCompanyCnpj() {
		return this.cliCompanyCnpj;
	}

	public void setCliCompanyCnpj(String cliCompanyCnpj) {
		this.cliCompanyCnpj = cliCompanyCnpj;
	}

	@Column(name = "cli_company_ie", unique = true, nullable = false, length = 13)
	public String getCliCompanyIe() {
		return this.cliCompanyIe;
	}

	public void setCliCompanyIe(String cliCompanyIe) {
		this.cliCompanyIe = cliCompanyIe;
	}

	@Column(name = "cli_company_phone_code", nullable = false, length = 2)
	public String getCliCompanyPhoneCode() {
		return this.cliCompanyPhoneCode;
	}

	public void setCliCompanyPhoneCode(String cliCompanyPhoneCode) {
		this.cliCompanyPhoneCode = cliCompanyPhoneCode;
	}

	@Column(name = "cli_company_phone_number", unique = true, nullable = false, length = 9)
	public String getCliCompanyPhoneNumber() {
		return this.cliCompanyPhoneNumber;
	}

	public void setCliCompanyPhoneNumber(String cliCompanyPhoneNumber) {
		this.cliCompanyPhoneNumber = cliCompanyPhoneNumber;
	}

	@Column(name = "cli_company_email", length = 70)
	public String getCliCompanyEmail() {
		return this.cliCompanyEmail;
	}

	public void setCliCompanyEmail(String cliCompanyEmail) {
		this.cliCompanyEmail = cliCompanyEmail;
	}

	@Column(name = "cli_company_addr", nullable = false, length = 90)
	public String getCliCompanyAddr() {
		return this.cliCompanyAddr;
	}

	public void setCliCompanyAddr(String cliCompanyAddr) {
		this.cliCompanyAddr = cliCompanyAddr;
	}

	@Column(name = "cli_company_addr_num", nullable = false, length = 12)
	public String getCliCompanyAddrNum() {
		return this.cliCompanyAddrNum;
	}

	public void setCliCompanyAddrNum(String cliCompanyAddrNum) {
		this.cliCompanyAddrNum = cliCompanyAddrNum;
	}

	@Column(name = "cli_company_postal", nullable = false, length = 9)
	public String getCliCompanyPostal() {
		return this.cliCompanyPostal;
	}

	public void setCliCompanyPostal(String cliCompanyPostal) {
		this.cliCompanyPostal = cliCompanyPostal;
	}

	@Column(name = "cli_company_district", nullable = false, length = 60)
	public String getCliCompanyDistrict() {
		return this.cliCompanyDistrict;
	}

	public void setCliCompanyDistrict(String cliCompanyDistrict) {
		this.cliCompanyDistrict = cliCompanyDistrict;
	}

	@Column(name = "cli_company_city", nullable = false, length = 60)
	public String getCliCompanyCity() {
		return this.cliCompanyCity;
	}

	public void setCliCompanyCity(String cliCompanyCity) {
		this.cliCompanyCity = cliCompanyCity;
	}

	@Column(name = "cli_company_state", nullable = false, length = 2)
	public String getCliCompanyState() {
		return this.cliCompanyState;
	}

	public void setCliCompanyState(String cliCompanyState) {
		this.cliCompanyState = cliCompanyState;
	}

	@Column(name = "cli_password", nullable = false, length = 25)
	public String getCliPassword() {
		return this.cliPassword;
	}

	public void setCliPassword(String cliPassword) {
		this.cliPassword = cliPassword;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "clients")
	public Set<ProductOrder> getProductOrders() {
		return this.productOrders;
	}

	public void setProductOrders(Set<ProductOrder> productOrders) {
		this.productOrders = productOrders;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "clients")
	public Set<Reviews> getReviewses() {
		return this.reviewses;
	}

	public void setReviewses(Set<Reviews> reviewses) {
		this.reviewses = reviewses;
	}

}
