package com.hamadaintranet.entity;
// Generated Oct 13, 2020 10:20:22 AM by Hibernate Tools 5.2.10.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Reviews generated by hbm2java
 */
@Entity
@Table(name = "reviews", catalog = "hamadadb")
public class Reviews implements java.io.Serializable {

	private long reviewId;
	private Clients clients;
	private Products products;
	private int rating;
	private String headline;
	private String reviewComment;
	private Date reviewTime;

	public Reviews() {
	}

	public Reviews(long reviewId, Clients clients, Products products, int rating, String headline, String reviewComment,
			Date reviewTime) {
		this.reviewId = reviewId;
		this.clients = clients;
		this.products = products;
		this.rating = rating;
		this.headline = headline;
		this.reviewComment = reviewComment;
		this.reviewTime = reviewTime;
	}

	@Id

	@Column(name = "review_id", unique = true, nullable = false)
	public long getReviewId() {
		return this.reviewId;
	}

	public void setReviewId(long reviewId) {
		this.reviewId = reviewId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "cli_id", nullable = false)
	public Clients getClients() {
		return this.clients;
	}

	public void setClients(Clients clients) {
		this.clients = clients;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "prod_id", nullable = false)
	public Products getProducts() {
		return this.products;
	}

	public void setProducts(Products products) {
		this.products = products;
	}

	@Column(name = "rating", nullable = false)
	public int getRating() {
		return this.rating;
	}

	public void setRating(int rating) {
		this.rating = rating;
	}

	@Column(name = "headline", nullable = false, length = 120)
	public String getHeadline() {
		return this.headline;
	}

	public void setHeadline(String headline) {
		this.headline = headline;
	}

	@Column(name = "review_comment", nullable = false, length = 500)
	public String getReviewComment() {
		return this.reviewComment;
	}

	public void setReviewComment(String reviewComment) {
		this.reviewComment = reviewComment;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "review_time", nullable = false, length = 19)
	public Date getReviewTime() {
		return this.reviewTime;
	}

	public void setReviewTime(Date reviewTime) {
		this.reviewTime = reviewTime;
	}

}
